import{a as q,S as B,i as n}from"./assets/vendor-DaWAOjWS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const P="https://pixabay.com/api/",R="52593892-e60586d66f6e8b7acef69d169";let l=1;const M=15;async function f(s,t=!1){t&&(l=1);const r={key:R,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:l};try{const i=await q.get(P,{params:r});return l+=1,i.data}catch(i){throw console.error("Error fetching images:",i),i}}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".load-more-btn"),$=new B(".gallery a",{captionsData:"alt",captionDelay:250});function b(s){const t=s.map(({webformatURL:r,largeImageURL:i,tags:e,likes:o,views:a,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${r}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${v}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),$.refresh()}function E(){p.innerHTML=""}function L(){g.classList.remove("hidden")}function h(){g.classList.add("hidden")}function O(){y.classList.remove("hidden")}function x(){y.classList.add("hidden")}const d=document.querySelector(".form"),m=document.querySelector(".load-more-btn");let w="",u=0,c=0;h();x();d.addEventListener("submit",async s=>{s.preventDefault();const t=d.elements["search-text"].value.trim();if(!t){n.error({message:"Please enter a search term!",position:"topRight"});return}E(),L(),w=t,c=0;try{const r=await f(t,!0);if(u=r.totalHits,!r.hits.length){n.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(r.hits),c+=r.hits.length,c<u?O():n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(r){n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Submit error:",r)}finally{h(),d.reset()}});m.addEventListener("click",async()=>{L();try{const s=await f(w);b(s.hits),c+=s.hits.length;const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}c>=u&&(m.style.display="none",n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){n.error({message:"Failed to load more images.",position:"topRight"}),console.error("Load more error:",s)}finally{h()}});
//# sourceMappingURL=index.js.map
