import{a as B,S as P,i as $}from"./assets/vendor-DaWAOjWS.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",O="52593892-e60586d66f6e8b7acef69d169";let l=1;const x=15;async function h(t,r=!1){r&&(l=1);const n={key:O,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:x},a=await B.get(M,{params:n});return l+=1,a.data}const y=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector(".load-more-btn"),E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function b(t){const r=t.map(({webformatURL:n,largeImageURL:a,tags:e,likes:o,views:i,comments:w,downloads:q})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${n}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${q}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",r),E.refresh()}function H(){y.innerHTML=""}function L(){p.classList.remove("hidden")}function f(){p.classList.add("hidden")}function S(){g.classList.remove("hidden")}function m(){g.classList.add("hidden")}function A(){const t=document.querySelector(".gallery-item");if(!t)return;const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}const d=document.querySelector(".form"),D=document.querySelector(".load-more-btn");let v="",u=0,c=0;function s(t,r){$[t]({message:r,position:"topRight",timeout:3e3})}f();m();d.addEventListener("submit",async t=>{t.preventDefault();const r=d.elements["search-text"].value.trim();if(!r){s("error","Please enter a search term!");return}H(),L(),m(),v=r,c=0;try{const n=await h(r,!0);if(u=n.totalHits,!n.hits.length){s("error","Sorry, there are no images matching your search query. Please try again!");return}b(n.hits),c+=n.hits.length,c<u?S():s("info","We're sorry, but you've reached the end of search results.")}catch(n){s("error","Something went wrong. Please try again later."),console.error("Submit error:",n)}finally{f(),d.reset()}});D.addEventListener("click",async()=>{m(),L();try{const t=await h(v);b(t.hits),c+=t.hits.length,A(),c>=u?s("info","We're sorry, but you've reached the end of search results."):S()}catch(t){s("error","Failed to load more images."),console.error("Load more error:",t)}finally{f()}});
//# sourceMappingURL=index.js.map
